### ISSUE TITLE
Cannot use it without nodejs

### ISSUE THREAD

**Issue by cdarken** [bendrucker/angular-countdown#2]
It seems like there's no way to use this library without nodejs. I'm trying to use it with ionic framework and I can't import the module.

**Comment by bendrucker** [comment]
[Browserify](http://browserify.org/), technically. Which is awesome and you should absolutely look into. I'll release a UMD version now as I typically do for projects once I've dogfooded them for a little bit. 

https://github.com/bendrucker/angular-countdown/blob/v1.2.1/release/angular-countdown.js

So as of 1.2.1 you can install from Bower and just include the script tag. Looking forward to getting feedback since this is pretty new.

**Comment by cdarken** [comment]
Yeah, I know about browserify and I know it's awesome, but I'm using gulp to concatenate and minify my js, so browserify is not an option for me. I will try the new version again, thank you.

**Comment by bendrucker** [comment]
Right, the point is to not just concatenate your scripts :smile: 

Blog post coming soon on Browserify + Angular

**Comment by cdarken** [comment]
Yeah. Not usable for me then.

**Comment by bendrucker** [comment]
Not sure what you mean by not usable.

**Comment by cdarken** [comment]
I want to be able to include your js and just add the module name to my module's dependencies. I cannot do this now, or I'm not using the correct module name. Is it 'angular-countdown' ?

**Comment by bendrucker** [comment]
It's `'countdown'`. I publish with the angular prefix but remove the prefix in the module names. 

https://github.com/bendrucker/angular-countdown/blob/b41a58db41bdaf5cbc7527424af352ab386d369e/src/index.js#L7

I'll document the name.

**Comment by cdarken** [comment]
Yeah, line 13 of the generated js. I'm blind. Thanks a lot.

**Comment by bendrucker** [comment]
No worries! My mistake for forgetting to include it in the readme.
